# Classification Algorithms Assignment


## 1. Linear Classification Algorithms

Algorithms:
1. Logistic Regression
2. Perceptron
3. Ridge Classifier
4. Linear Discriminant Analysis (LDA)
5. Quadratic Discriminant Analysis (QDA)
6. Linear Support Vector Machine (Linear SVM)
7. Stochastic Gradient Descent (SGD Classifier)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time

from sklearn.datasets import load_iris, load_breast_cancer, load_digits, load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

RANDOM_STATE = 42
sns.set_theme(style="whitegrid")

def evaluate_model(model, X_train, X_test, y_train, y_test, name):
    start = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - start
    pred = model.predict(X_test)
    print(f"\n{name}")
    print("=" * len(name))
    print("Accuracy :", round(accuracy_score(y_test, pred), 4))
    print("Precision:", round(precision_score(y_test, pred, average="weighted", zero_division=0), 4))
    print("Recall   :", round(recall_score(y_test, pred, average="weighted", zero_division=0), 4))
    print("F1-score :", round(f1_score(y_test, pred, average="weighted", zero_division=0), 4))
    print("Training time:", round(train_time, 4), "seconds")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, pred))
    return model, pred, train_time

iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

In [2]:
from sklearn.linear_model import LogisticRegression, Perceptron, RidgeClassifier, SGDClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.svm import LinearSVC

linear_models = [
    ("Logistic Regression", make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))),
    ("Perceptron", make_pipeline(StandardScaler(), Perceptron(random_state=RANDOM_STATE))),
    ("Ridge Classifier", make_pipeline(StandardScaler(), RidgeClassifier())),
    ("LDA", LinearDiscriminantAnalysis()),
    ("QDA", make_pipeline(StandardScaler(), QuadraticDiscriminantAnalysis())),
    ("Linear SVM", make_pipeline(StandardScaler(), LinearSVC(random_state=RANDOM_STATE, max_iter=5000))),
    ("SGD Classifier", make_pipeline(StandardScaler(), SGDClassifier(random_state=RANDOM_STATE, max_iter=2000, tol=1e-3)))
]

results = []
trained_models = {}

for name, model in linear_models:
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    trained_models[name] = fitted
    results.append({
        "Algorithm": name,
        "Category": "Linear Classification",
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_test, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_test, pred, average="weighted", zero_division=0),
        "Training Time (s)": train_time
    })

pd.DataFrame(results)


Logistic Regression
Accuracy : 0.9333
Precision: 0.9333
Recall   : 0.9333
F1-score : 0.9333
Training time: 0.014 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]

Perceptron
Accuracy : 0.8667
Precision: 0.875
Recall   : 0.8667
F1-score : 0.8653
Training time: 0.0068 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  7  3]
 [ 0  1  9]]

Ridge Classifier
Accuracy : 0.7667
Precision: 0.7766
Recall   : 0.7667
F1-score : 0.7613
Training time: 0.0101 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  5  5]
 [ 0  2  8]]

LDA
===
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-score : 1.0
Training time: 0.004 seconds

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]

QDA
===
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-score : 1.0
Training time: 0.0049 seconds

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]

Linear SVM
Accuracy : 0.9
Precision: 0.9024
Recall   : 0.9
F1-score : 0.8997
Training time: 0.0033 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  8  2]
 [ 0  1  9]]

SGD

,Algorithm,Category,Accuracy,Precision,Recall,F1-score,Training Time (s)
0,Logistic Regression,Linear Classification,0.933333,0.933333,0.933333,0.933333,0.014001
1,Perceptron,Linear Classification,0.866667,0.875000,0.866667,0.865320,0.006824
2,Ridge Classifier,Linear Classification,0.766667,0.776557,0.766667,0.761296,0.010096
3,LDA,Linear Classification,1.000000,1.000000,1.000000,1.000000,0.003959
4,QDA,Linear Classification,1.000000,1.000000,1.000000,1.000000,0.004865
5,Linear SVM,Linear Classification,0.900000,0.902357,0.900000,0.899749,0.003256
6,SGD Classifier,Linear Classification,0.933333,0.933333,0.933333,0.933333,0.006539


## 2. Distance-Based Algorithms

Algorithms:
1. k-Nearest Neighbors (KNN)
2. Radius Neighbors Classifier

In [3]:
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier

distance_models = [
    ("KNN", make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5))),
    ("Radius Neighbors", make_pipeline(StandardScaler(), RadiusNeighborsClassifier(radius=2.0, outlier_label="most_frequent")))
]

for name, model in distance_models:
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    results.append({
        "Algorithm": name,
        "Category": "Distance-Based",
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_test, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_test, pred, average="weighted", zero_division=0),
        "Training Time (s)": train_time
    })


KNN
===
Accuracy : 0.9333
Precision: 0.9444
Recall   : 0.9333
F1-score : 0.9327
Training time: 0.0038 seconds

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]

Radius Neighbors
Accuracy : 0.8333
Precision: 0.835
Recall   : 0.8333
F1-score : 0.8329
Training time: 0.0042 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  8  2]
 [ 0  3  7]]


## 3. Tree-Based Algorithms

Algorithms:
1. Decision Tree
2. Extra Trees (Extremely Randomized Trees)

In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier

tree_models = [
    ("Decision Tree", DecisionTreeClassifier(random_state=RANDOM_STATE)),
    ("Extra Trees", ExtraTreesClassifier(n_estimators=100, random_state=RANDOM_STATE))
]

for name, model in tree_models:
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    results.append({
        "Algorithm": name,
        "Category": "Tree-Based",
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_test, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_test, pred, average="weighted", zero_division=0),
        "Training Time (s)": train_time
    })


Decision Tree
Accuracy : 0.9333
Precision: 0.9333
Recall   : 0.9333
F1-score : 0.9333
Training time: 0.0043 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]

Extra Trees
Accuracy : 0.9333
Precision: 0.9333
Recall   : 0.9333
F1-score : 0.9333
Training time: 0.1515 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]


## 4. Ensemble Methods - Bagging

Algorithms:
1. Random Forest
2. Bagging Classifier

In [5]:
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier

bagging_models = [
    ("Random Forest", RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE)),
    ("Bagging Classifier", BaggingClassifier(n_estimators=100, random_state=RANDOM_STATE))
]

for name, model in bagging_models:
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    results.append({
        "Algorithm": name,
        "Category": "Ensemble - Bagging",
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_test, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_test, pred, average="weighted", zero_division=0),
        "Training Time (s)": train_time
    })


Random Forest
Accuracy : 0.9
Precision: 0.9024
Recall   : 0.9
F1-score : 0.8997
Training time: 0.2578 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]

Bagging Classifier
Accuracy : 0.9667
Precision: 0.9697
Recall   : 0.9667
F1-score : 0.9666
Training time: 0.3562 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


## 5. Ensemble Methods - Boosting

Algorithms:
1. AdaBoost
2. Gradient Boosting
3. XGBoost
4. LightGBM
5. CatBoost

In [21]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

boosting_models = [
    ("AdaBoost", AdaBoostClassifier(n_estimators=100, random_state=RANDOM_STATE)),
    ("Gradient Boosting", GradientBoostingClassifier(n_estimators=100, random_state=RANDOM_STATE))
]

for name, model in boosting_models:
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    results.append({
        "Algorithm": name,
        "Category": "Ensemble - Boosting",
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_test, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_test, pred, average="weighted", zero_division=0),
        "Training Time (s)": train_time
    })


AdaBoost
Accuracy : 0.9333
Precision: 0.9333
Recall   : 0.9333
F1-score : 0.9333
Training time: 0.3098 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]

Gradient Boosting
Accuracy : 0.9667
Precision: 0.9697
Recall   : 0.9667
F1-score : 0.9666
Training time: 0.4845 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [7]:
try:
    from xgboost import XGBClassifier
    model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3,
                          random_state=RANDOM_STATE, eval_metric="mlogloss")
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, "XGBoost")
    results.append({"Algorithm":"XGBoost","Category":"Ensemble - Boosting",
                    "Accuracy":accuracy_score(y_test,pred),
                    "Precision":precision_score(y_test,pred,average="weighted",zero_division=0),
                    "Recall":recall_score(y_test,pred,average="weighted",zero_division=0),
                    "F1-score":f1_score(y_test,pred,average="weighted",zero_division=0),
                    "Training Time (s)":train_time})
except ImportError:
    print("XGBoost not installed. Install with: pip install xgboost")

try:
    from lightgbm import LGBMClassifier
    model = LGBMClassifier(n_estimators=100, learning_rate=0.1, random_state=RANDOM_STATE, verbose=-1)
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, "LightGBM")
    results.append({"Algorithm":"LightGBM","Category":"Ensemble - Boosting",
                    "Accuracy":accuracy_score(y_test,pred),
                    "Precision":precision_score(y_test,pred,average="weighted",zero_division=0),
                    "Recall":recall_score(y_test,pred,average="weighted",zero_division=0),
                    "F1-score":f1_score(y_test,pred,average="weighted",zero_division=0),
                    "Training Time (s)":train_time})
except ImportError:
    print("LightGBM not installed. Install with: pip install lightgbm")

try:
    from catboost import CatBoostClassifier
    model = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=5,
                               random_seed=RANDOM_STATE, verbose=False)
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, "CatBoost")
    results.append({"Algorithm":"CatBoost","Category":"Ensemble - Boosting",
                    "Accuracy":accuracy_score(y_test,pred),
                    "Precision":precision_score(y_test,pred,average="weighted",zero_division=0),
                    "Recall":recall_score(y_test,pred,average="weighted",zero_division=0),
                    "F1-score":f1_score(y_test,pred,average="weighted",zero_division=0),
                    "Training Time (s)":train_time})
except ImportError:
    print("CatBoost not installed. Install with: pip install catboost")


XGBoost
Accuracy : 0.9333
Precision: 0.9333
Recall   : 0.9333
F1-score : 0.9333
Training time: 0.7211 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]
LightGBM not installed. Install with: pip install lightgbm
CatBoost not installed. Install with: pip install catboost


## 6. Margin-Based Methods

Algorithms:
1. Support Vector Machine (SVM)
2. Kernel SVM

In [8]:
from sklearn.svm import SVC

margin_models = [
    ("SVM - Linear Kernel", make_pipeline(StandardScaler(), SVC(kernel="linear", random_state=RANDOM_STATE))),
    ("Kernel SVM - RBF", make_pipeline(StandardScaler(), SVC(kernel="rbf", random_state=RANDOM_STATE)))
]

for name, model in margin_models:
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    results.append({
        "Algorithm": name,
        "Category": "Margin-Based",
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_test, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_test, pred, average="weighted", zero_division=0),
        "Training Time (s)": train_time
    })


SVM - Linear Kernel
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-score : 1.0
Training time: 0.0208 seconds

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]

Kernel SVM - RBF
Accuracy : 0.9667
Precision: 0.9697
Recall   : 0.9667
F1-score : 0.9666
Training time: 0.0054 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


## 7. Probabilistic Algorithms

Algorithms listed:
1. Naive Bayes (Gaussian, Multinomial, Bernoulli)
2. Bayesian Networks

In [9]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

nb_models = [
    ("Gaussian Naive Bayes", GaussianNB()),
    ("Bernoulli Naive Bayes", make_pipeline(StandardScaler(), BernoulliNB()))
]

for name, model in nb_models:
    fitted, pred, train_time = evaluate_model(model, X_train, X_test, y_train, y_test, name)
    results.append({
        "Algorithm": name,
        "Category": "Probabilistic",
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="weighted", zero_division=0),
        "Recall": recall_score(y_test, pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_test, pred, average="weighted", zero_division=0),
        "Training Time (s)": train_time
    })

from sklearn.preprocessing import MinMaxScaler
X_train_nonnegative = MinMaxScaler().fit_transform(X_train)
scaler_mnb = MinMaxScaler()
X_train_mnb = scaler_mnb.fit_transform(X_train)
X_test_mnb = scaler_mnb.transform(X_test)

mnb = MultinomialNB()
fitted, pred, train_time = evaluate_model(mnb, X_train_mnb, X_test_mnb, y_train, y_test, "Multinomial Naive Bayes")
results.append({
    "Algorithm":"Multinomial Naive Bayes","Category":"Probabilistic",
    "Accuracy":accuracy_score(y_test,pred),
    "Precision":precision_score(y_test,pred,average="weighted",zero_division=0),
    "Recall":recall_score(y_test,pred,average="weighted",zero_division=0),
    "F1-score":f1_score(y_test,pred,average="weighted",zero_division=0),
    "Training Time (s)":train_time
})


Gaussian Naive Bayes
Accuracy : 0.9667
Precision: 0.9697
Recall   : 0.9667
F1-score : 0.9666
Training time: 0.0047 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

Bernoulli Naive Bayes
Accuracy : 0.7333
Precision: 0.8194
Recall   : 0.7333
F1-score : 0.6706
Training time: 0.0056 seconds

Confusion Matrix:
[[10  0  0]
 [ 2  2  6]
 [ 0  0 10]]

Multinomial Naive Bayes
Accuracy : 0.8333
Precision: 0.835
Recall   : 0.8333
F1-score : 0.8329
Training time: 0.0031 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  7  3]
 [ 0  2  8]]


## 8. Neural Network-Based Algorithms

Algorithms:
1. Multilayer Perceptron (MLP)
2. Convolutional Neural Networks (CNN)
3. Recurrent Neural Networks (RNN)
4. LSTM / GRU
5. Transformers

In [11]:
from sklearn.neural_network import MLPClassifier

mlp = make_pipeline(
    StandardScaler(),
    MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=500, random_state=RANDOM_STATE, early_stopping=True)
)
fitted, pred, train_time = evaluate_model(mlp, X_train, X_test, y_train, y_test, "Multilayer Perceptron (MLP)")
results.append({
    "Algorithm":"MLP","Category":"Neural Network",
    "Accuracy":accuracy_score(y_test,pred),
    "Precision":precision_score(y_test,pred,average="weighted",zero_division=0),
    "Recall":recall_score(y_test,pred,average="weighted",zero_division=0),
    "F1-score":f1_score(y_test,pred,average="weighted",zero_division=0),
    "Training Time (s)":train_time
})


Multilayer Perceptron (MLP)
Accuracy : 0.6667
Precision: 0.5
Recall   : 0.6667
F1-score : 0.5556
Training time: 0.0537 seconds

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0 10  0]]


In [12]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("PyTorch device:", device)

PyTorch device: cpu


In [13]:
digits = load_digits()
X_img = torch.tensor(digits.images[:, None, :, :], dtype=torch.float32) / 16.0
y_img = torch.tensor(digits.target, dtype=torch.long)

img_train, img_test, y_img_train, y_img_test = train_test_split(
    X_img, y_img, test_size=0.2, random_state=RANDOM_STATE, stratify=y_img
)

class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(1, 16, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(32 * 2 * 2, 64), nn.ReLU(),
            nn.Linear(64, 10)
        )
    def forward(self, x):
        return self.net(x)

cnn = SimpleCNN().to(device)
loader = DataLoader(TensorDataset(img_train, y_img_train), batch_size=64, shuffle=True)
optimizer = torch.optim.Adam(cnn.parameters(), lr=0.001)
loss_fn = nn.CrossEntropyLoss()

for epoch in range(3):
    cnn.train()
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        loss = loss_fn(cnn(xb), yb)
        loss.backward()
        optimizer.step()

cnn.eval()
with torch.no_grad():
    pred = cnn(img_test.to(device)).argmax(1).cpu()
print("CNN Accuracy:", round(accuracy_score(y_img_test, pred), 4))

CNN Accuracy: 0.7861


In [14]:
torch.manual_seed(RANDOM_STATE)

n_samples, seq_len, input_size = 1000, 20, 4
X_seq = torch.randn(n_samples, seq_len, input_size)
y_seq = (X_seq.mean(dim=(1, 2)) > 0).long()

seq_train, seq_test, y_seq_train, y_seq_test = train_test_split(
    X_seq, y_seq, test_size=0.2, random_state=RANDOM_STATE, stratify=y_seq
)

class SequenceClassifier(nn.Module):
    def __init__(self, cell="RNN"):
        super().__init__()
        if cell == "RNN":
            self.rnn = nn.RNN(input_size, 32, batch_first=True)
        elif cell == "LSTM":
            self.rnn = nn.LSTM(input_size, 32, batch_first=True)
        else:
            self.rnn = nn.GRU(input_size, 32, batch_first=True)
        self.fc = nn.Linear(32, 2)

    def forward(self, x):
        out, _ = self.rnn(x)
        return self.fc(out[:, -1, :])

for cell in ["RNN", "LSTM", "GRU"]:
    model = SequenceClassifier(cell).to(device)
    loader = DataLoader(TensorDataset(seq_train, y_seq_train), batch_size=64, shuffle=True)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    loss_fn = nn.CrossEntropyLoss()

    for epoch in range(3):
        model.train()
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()
            loss = loss_fn(model(xb), yb)
            loss.backward()
            optimizer.step()

    model.eval()
    with torch.no_grad():
        pred = model(seq_test.to(device)).argmax(1).cpu()
    print(f"{cell} Accuracy:", round(accuracy_score(y_seq_test, pred), 4))

RNN Accuracy: 0.62
LSTM Accuracy: 0.705
GRU Accuracy: 0.745


In [15]:
class SimpleTransformer(nn.Module):
    def __init__(self):
        super().__init__()
        d_model = 32
        self.proj = nn.Linear(input_size, d_model)
        layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=4, batch_first=True)
        self.encoder = nn.TransformerEncoder(layer, num_layers=2)
        self.fc = nn.Linear(d_model, 2)

    def forward(self, x):
        x = self.proj(x)
        x = self.encoder(x)
        return self.fc(x.mean(dim=1))

transformer = SimpleTransformer().to(device)
loader = DataLoader(TensorDataset(seq_train, y_seq_train), batch_size=64, shuffle=True)
optimizer = torch.optim.Adam(transformer.parameters(), lr=0.001)
loss_fn = nn.CrossEntropyLoss()

for epoch in range(3):
    transformer.train()
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        loss = loss_fn(transformer(xb), yb)
        loss.backward()
        optimizer.step()

transformer.eval()
with torch.no_grad():
    pred = transformer(seq_test.to(device)).argmax(1).cpu()
print("Transformer Accuracy:", round(accuracy_score(y_seq_test, pred), 4))

Transformer Accuracy: 0.925


## 9. Instance & Rule-Based Algorithms

Algorithms:
1. OneR
2. RIPPER
3. Rule-based Classifiers
4. Nearest Centroid

In [20]:
from sklearn.neighbors import NearestCentroid

nearest_centroid = NearestCentroid()
fitted, pred, train_time = evaluate_model(
    nearest_centroid, X_train, X_test, y_train, y_test, "Nearest Centroid"
)
results.append({
    "Algorithm":"Nearest Centroid","Category":"Instance & Rule-Based",
    "Accuracy":accuracy_score(y_test,pred),
    "Precision":precision_score(y_test,pred,average="weighted",zero_division=0),
    "Recall":recall_score(y_test,pred,average="weighted",zero_division=0),
    "F1-score":f1_score(y_test,pred,average="weighted",zero_division=0),
    "Training Time (s)":train_time
})


Nearest Centroid
Accuracy : 0.9
Precision: 0.9024
Recall   : 0.9
F1-score : 0.8997
Training time: 0.0026 seconds

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]
